version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - frn_network
  data_operations:
    build:
      context: .
      dockerfile: data_operations/fetch_operations.dockerfile
    container_name: 'fetch_service'
    env_file:
      - .env
    networks:
      - frn_network
  web-services:
    build:
      context: .
      dockerfile: ./web_service/webservice.dockerfile
    container_name: 'web-services'
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - frn_network
  db:
    image: postgres:15.2-alpine
    container_name: 'postgredb'
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
    networks:
      - frn_network
      
networks:
  frn_network:
    driver: bridge
